# Generated by Django 3.0.8 on 2020-07-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityPeriods',
            new_name='ActivityPeriod',
        ),
    ]
