# Generated by Django 3.0.8 on 2020-07-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0003_auto_20200706_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='user',
        ),
    ]
