# Generated by Django 3.0.8 on 2020-07-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0005_auto_20200706_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jsonapi.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
